export const AIRTABLE_TABLE_MAP: Record<string, { tableId: string; monthFieldId: string }> = {
  "Berlin Döner":         { tableId: "tbl1u7GxL0s3jlnEw", monthFieldId: "fld5TbWjFSUx1c0cR" },
  "Asian BBQ":            { tableId: "tblwYXlV8LpCwHCoJ", monthFieldId: "fldNAfwQBmdTpgbXD" },
  "Stuvsta & östermalm":  { tableId: "tbltAmoExe7AXm0RN", monthFieldId: "fldzETwYq1R6hg34R" },
  "South side":           { tableId: "tblLPw7zdn3pC9jOR", monthFieldId: "fldO8LIh13z6XiZSy" },
  "k25":                  { tableId: "tbl3m9a8RR6xci6cc", monthFieldId: "fld4oHbBqPFdi0adT" },
  "Dripp'n Burgers":      { tableId: "tbl95LfsliAWQ7PfT", monthFieldId: "fldujz5T6qrA1dWe0" },
  "Keb":                  { tableId: "tbljQKYG15GOp9VFW", monthFieldId: "fldn8VxnYCVPlKgUE" },
  "Dunder smash":         { tableId: "tblZyq8o6DIAipC5g", monthFieldId: "fldb0OqKg1LQxu6qL" },
  "Chop Chop":            { tableId: "tblJGSZ9SnUeyVRlt", monthFieldId: "fldtgGACBDq21VPHn" },
  "Mazraa":               { tableId: "tblszvHemgW3iD5k5", monthFieldId: "fld9PRp3d3K5YYSFv" },
  "Avidental":            { tableId: "tblxftsvCG3GiHQzQ", monthFieldId: "fld5K7bGFX2Z7G9K4" },
  "Bram's burger":        { tableId: "tbljY8HjyjEyhaOx7", monthFieldId: "fld6cRDoqkcXXtTaj" },
  "Falafel baren":        { tableId: "tbljofsrSZlECKYMp", monthFieldId: "fldSrvSli8aO3B4ES" },
  "Berra & burras":       { tableId: "tblhXxO9jGx0OWQvy", monthFieldId: "fldrL6Vy0gKzMqaQH" },
  "Full moon wok":        { tableId: "tblx3ntavohk0jM7Z", monthFieldId: "fldrMft5HLNNqI9wF" },
  "Fluffy house":         { tableId: "tbl83TWa2o4QeQNCp", monthFieldId: "fldhvXOkxF6DquZwG" },
  "Sushi revelution":     { tableId: "tbl6aPVxRierRfp6z", monthFieldId: "fldaZoboc2CAqrOTO" },
  "Qopla":                { tableId: "tbl4hlAPXoGyVchpv", monthFieldId: "fldZDBioDPzxFQEXl" },
  "Stekt burger & stuff": { tableId: "tblnEcY6fReijhrJU", monthFieldId: "fldZT2dHajGYn7t1Q" },
  "Kebab dudes":          { tableId: "tblcktXSXxbfGVcht", monthFieldId: "fldWkMI4Ks2zwCEt7" },
  "Rosa Pantern":         { tableId: "tblUcp6AgtCZsCFIN", monthFieldId: "fldTiJHEStdnFBsRh" },
  "Holly Bush":           { tableId: "tblsgTveLXhdNWsoX", monthFieldId: "fldDLlYkSxSZ6K47h" },
}
