// Keys match INIT_KUNDER names exactly (src/lib/data.ts)
// monthFieldName = the actual field name as returned by Airtable Records API
export const AIRTABLE_TABLE_MAP: Record<string, { tableId: string; monthFieldName: string }> = {
  "Berlin Doner":         { tableId: "tbl1u7GxL0s3jlnEw", monthFieldName: "Field 5" },
  "Asian BBQ":            { tableId: "tblwYXlV8LpCwHCoJ", monthFieldName: "Field 7" },
  "Ostermalmsgrillen":    { tableId: "tbltAmoExe7AXm0RN", monthFieldName: "Field 5" },
  "Southside Burgers":    { tableId: "tblLPw7zdn3pC9jOR", monthFieldName: "Field 5" },
  "K25":                  { tableId: "tbl3m9a8RR6xci6cc", monthFieldName: "Field 7" },
  "Drippn Burgers":       { tableId: "tbl95LfsliAWQ7PfT", monthFieldName: "Field 5" },
  "KEB":                  { tableId: "tbljQKYG15GOp9VFW", monthFieldName: "Field 5" },
  "Dunder Smash":         { tableId: "tblZyq8o6DIAipC5g", monthFieldName: "Dunder smash" },
  "ChopChop":             { tableId: "tblJGSZ9SnUeyVRlt", monthFieldName: "Field 6" },
  "Mazra'a":              { tableId: "tblszvHemgW3iD5k5", monthFieldName: "Field 7" },
  "Avidental":            { tableId: "tblxftsvCG3GiHQzQ", monthFieldName: "Field 7" },
  "Brams Burgers":        { tableId: "tbljY8HjyjEyhaOx7", monthFieldName: "Field 7" },
  "Falafelbaren":         { tableId: "tbljofsrSZlECKYMp", monthFieldName: "Field 7" },
  "Berra Burras":         { tableId: "tblhXxO9jGx0OWQvy", monthFieldName: "Field 5" },
  "Fullmoon Wok":         { tableId: "tblx3ntavohk0jM7Z", monthFieldName: "Field 7" },
  "Fluffy House":         { tableId: "tbl83TWa2o4QeQNCp", monthFieldName: "Field 7" },
  "Sushi Revolution":     { tableId: "tbl6aPVxRierRfp6z", monthFieldName: "Field 7" },
  "Qopla":                { tableId: "tbl4hlAPXoGyVchpv", monthFieldName: "Field 5" },
  "STEKT Burger":         { tableId: "tblnEcY6fReijhrJU", monthFieldName: "Field 5" },
  "Kebabdudes":           { tableId: "tblcktXSXxbfGVcht", monthFieldName: "Field 7" },
  "Rosa Pantern":         { tableId: "tblUcp6AgtCZsCFIN", monthFieldName: "Month" },
  "The Holly Bush":       { tableId: "tblsgTveLXhdNWsoX", monthFieldName: "Field 7" },
}
